### ISSUE TITLE
LADy's Roadmap for Extension (Epic)

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/LADy#23]
@farinamhz @Lillliant 
Here is the overall plan for LADy's next iteration of development. Please create an issue for each sub development and link the issue page here:

**0-Web Demo**
Demo application: https://github.com/fani-lab/LADy/issues/32
- [x] running the existing version and adding to the codeline
- [x] design and features modifications
- [x] testing
- [ ] hosting and deployment #52
 
**1- Baselines**
- [ ] new state-of-the-art aspect detection baseline (preferably generation-based ones): https://github.com/fani-lab/LADy/issues/63

1.1. Supervised aspect term detection:
- [x] aspect term detection 2: Exploiting {BERT} for End-to-End Aspect-based Sentiment Analysis **=> needs integration**

1.2. Supervised aspect category detection: ??
- [x] Classification baseline for aspect term extraction --> (https://github.com/fani-lab/LADy/issues/42)

1.3. Unsupervised
- [ ] Unsupervised aspect category detection 1: Embarrassingly Simple Unsupervised Aspect Extraction **=> needs integration**

1.3.1. Unsupervised Topic-modeling-based:
- [x] Neural Topic Modeling --> https://github.com/fani-lab/LADy/issues/30
 CTM, ETM, BerTopic
- [x] Non-neural Topic Modeling: https://github.com/fani-lab/LADy/issues/12
    LDA,
    BTM: https://github.com/fani-lab/LADy/issues/5
    Random: https://github.com/fani-lab/LADy/issues/9

**2- Training Strategy**
- Augmentation
- [x] Back-translation module: https://github.com/fani-lab/LADy/issues/24
- [x] Word-alignment module: https://github.com/fani-lab/LADy/issues/26
- [x] Semantic comparison module: https://github.com/fani-lab/LADy/issues/27
- [x] Labelling the new results of back-translation: https://github.com/fani-lab/LADy/issues/29
- [x] Using the modules: https://github.com/fani-lab/LADy/issues/28
- [x] Normal

**3- Dataset**
- [x] Non-SemEval (MAMS) : https://github.com/fani-lab/LADy/issues/19
- [x] Unsolicited Reviews Dataset (Twitter): https://github.com/fani-lab/LADy/issues/55
- [x] SemEval14: https://github.com/fani-lab/LADy/issues/7
- [x] SemEval15: https://github.com/fani-lab/LADy/issues/7
- [x] SemEval16: https://github.com/fani-lab/LADy/issues/7
- [ ] MAMS dataset results

**4- Research Paper** 
- [x] Find one example that resurfaces an aspect

**5- Aggregation of results**
- [x] sub results from the aggregation file (i.e., from agg file to the tabular in paper)

**6- Resource paper**
- [x] testing the existing work and readme: https://github.com/fani-lab/LADy/issues/46
- [x] main flow diagram: https://github.com/fani-lab/LADy/issues/48
- [x] general paper writeup (to be continued)
- [x] integration of the aspect detection models
- [x] web app snapshots, deployment, and paper writeup: https://github.com/fani-lab/LADy/issues/32 and https://github.com/fani-lab/LADy/issues/52
- [x] running the experiments again to upload the results and resolving problem with sharepoint

**7- Languages**
- [x] With new languages (preferably low-resource ones): https://github.com/fani-lab/LADy/issues/70

**8- Translator**
- [x] Adding a new translator model: https://github.com/fani-lab/LADy/issues/66

**Comment by farinamhz** [comment]
@3ripleM

**Comment by farinamhz** [comment]
Hi @ErshadAmirreza,
Welcome to the LADy team!
Here is the epic issue for our tasks in LADy project.
In front of each task, you'll find its associated issue, where all logs and details about that task are stored.
If you have any questions, feel free to ask and I would be happy to help.
